name: Notificar a ntfy.sh

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a ntfy
        run: |
          curl -H "Title: Nuevo Push a main" \
               -H "Priority: high" \
               -d "Se hizo push a main y se ejecutó Hola Mundo con éxito 🎉" \
               https://ntfy.sh/devops-itla
